name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup React App
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Choose your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Netlify

        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: "dqttVQlBa1hdbO6QlUKSuz7Ff0XeYxxF2hfevXS4QCM"
